default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  port: 3306

development:
  primary:
    <<: *default
    host: db
    database: myapp_development
    password: password
  queue:
    <<: *default
    host: db
    database: myapp_development
    password: password
    migrations_paths: db/queue_migrate

test:
  <<: *default
  host: db
  database: myapp_test
  password: password

production:
  primary:
    <<: *default
    database: myapp_production
    url: <%= ENV['DATABASE_URL'] || Rails.application.credentials.dig(:production, :database_url) %>
  queue:
    <<: *default
    database: myapp_production
    url: <%= ENV['DATABASE_URL'] || Rails.application.credentials.dig(:production, :database_url) %>
    migrations_paths: db/queue_migrate