# Be sure to restart your server when you modify this file.
#
# This file eases your Rails 8.1 framework defaults upgrade.
#
# Uncomment each configuration one by one to switch to the new default.
# Once your application is ready to run with all new defaults, you can remove
# this file and set the `config.load_defaults` to `8.1`.
#
# Read the Guide for Upgrading Ruby on Rails for more info on each option.
# https://guides.rubyonrails.org/upgrading_ruby_on_rails.html
#
# このファイルは「8.1の新しいデフォルトを段階的に有効化する」ためのものです。
# ここに並んでいる設定はコメントアウトを外すと即時に挙動が変わります。
# 本番・開発の影響を確認しながら、項目ごとに解除してください。

###
# Skips escaping HTML entities and line separators. When set to `false`, the
# JSON renderer no longer escapes these to improve performance.
#
# Example:
#   class PostsController < ApplicationController
#     def index
#       render json: { key: "\u2028\u2029<>&" }
#     end
#   end
#
# Renders `{"key":"\u2028\u2029\u003c\u003e\u0026"}` with the previous default, but `{"key":"  <>&"}` with the config
# set to `false`.
#
# Applications that want to keep the escaping behavior can set the config to `true`.
#++
# 日本語メモ:
# JSONレスポンスのエスケープ挙動を変更します。
# これまで JSON 内の `<`, `>` などがエスケープされていましたが、`false` で高速化の代わりに
# そのまま返す挙動になります。
# 「JSONをそのまま返しても問題ない」ことが確認できたタイミングで解除してください。
# Rails.configuration.action_controller.escape_json_responses = false

###
# Skips escaping LINE SEPARATOR (U+2028) and PARAGRAPH SEPARATOR (U+2029) in JSON.
#
# Historically these characters were not valid inside JavaScript literal strings but that changed in ECMAScript 2019.
# As such it's no longer a concern in modern browsers: https://caniuse.com/mdn-javascript_builtins_json_json_superset.
#++
# 日本語メモ:
# JSON内の U+2028 / U+2029 のエスケープを省略します。
# 古いブラウザ互換を切り捨てられるなら解除してOKです。
# Rails.configuration.active_support.escape_js_separators_in_json = false

###
# Raises an error when order dependent finder methods (e.g. `#first`, `#second`) are called without `order` values
# on the relation, and the model does not have any order columns (`implicit_order_column`, `query_constraints`, or
# `primary_key`) to fall back on.
#
# The current behavior of not raising an error has been deprecated, and this configuration option will be removed in
# Rails 8.2.
#++
# 日本語メモ:
# `order` を指定していない `first/second/last` などの呼び出しに対してエラーを出します。
# 既存コードで「暗黙の順序」に依存していないことを確認できたら解除してください。
# Rails.configuration.active_record.raise_on_missing_required_finder_order_columns = true

###
# Controls how Rails handles path relative URL redirects.
# When set to `:raise`, Rails will raise an `ActionController::Redirecting::UnsafeRedirectError`
# for relative URLs without a leading slash, which can help prevent open redirect vulnerabilities.
#
# Example:
#   redirect_to "example.com"     # Raises UnsafeRedirectError
#   redirect_to "@attacker.com"   # Raises UnsafeRedirectError
#   redirect_to "/safe/path"      # Works correctly
#
# Applications that want to allow these redirects can set the config to `:log` (previous default)
# to only log warnings, or `:notify` to send ActiveSupport notifications.
#++
# 日本語メモ:
# `redirect_to "example.com"` のような相対URLリダイレクトをどう扱うかを制御します。
# セキュリティ観点では `:raise` が推奨です。既存挙動に影響がないことを確認できたら解除してください。
# Rails.configuration.action_controller.action_on_path_relative_redirect = :raise

###
# Use a Ruby parser to track dependencies between Action View templates
#++
# 日本語メモ:
# Action View のテンプレート依存関係の追跡方法を Ruby パーサーに切り替えます。
# 開発時のテンプレート再読み込みが正しく動作するか確認できたら解除してください。
# Rails.configuration.action_view.render_tracker = :ruby

###
# When enabled, hidden inputs generated by `form_tag`, `token_tag`, `method_tag`, and the hidden parameter fields
# included in `button_to` forms will omit the `autocomplete="off"` attribute.
#
# Applications that want to keep generating the `autocomplete` attribute for those tags can set it to `false`.
#++
# 日本語メモ:
# hidden input に `autocomplete="off"` を付けなくする設定です。
# 自動入力の挙動に影響がないことを確認できたら解除してください。
# Rails.configuration.action_view.remove_hidden_field_autocomplete = true
