plugins:
  - rubocop-factory_bot
  - rubocop-faker
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 3.4.3
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'config/environments/production.rb'
    - 'lib/tasks/mail_test_helper.rb'

# データベース関連とconfig設定ファイルは除外
Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'
    - 'config/environments/*.rb'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'lib/tasks/swagger.rake'
    - 'db/migrate/20250822164111_create_solid_queue_tables.rb'

# SolidQueueマイグレーションファイルのメトリクスを除外
Metrics/ClassLength:
  Exclude:
    - 'db/migrate/20250822164111_create_solid_queue_tables.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/20250822164111_create_solid_queue_tables.rb'

# マイグレーションファイルは既存のDeviseTokenAuthで修正不可
Rails/ThreeStateBooleanColumn:
  Exclude:
    - 'db/migrate/*.rb'
    - 'db/schema.rb'

Rails/ReversibleMigration:
  Exclude:
    - 'db/migrate/*.rb'

# Rakeタスクでの標準出力は許可
Rails/Output:
  Exclude:
    - 'lib/tasks/**/*'
